name: Deploy dist folder

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create and push dist folder
        run: |
          npm install
          npm run build
          mkdir -p temp-deploy
          cp -r dist/* temp-deploy/
          cd temp-deploy
          git init
          git remote add origin https://github.com/Zhuxb-Clouds/hrsrive.cn.git
          git add .
          git commit -m "Deploy dist folder"
          git push --force origin main
